name: Node.js CI with MySQL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    strategy:
      matrix:
        node-version: [18.11.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    # For client directory
    - name: Change into client directory
      run: cd client/
    - name: Install client dependencies
      run: npm install
      working-directory: ./client
    - name: Run client tests
      run: npm test
      working-directory: ./client
    
    - name: Create MySQL Tables
      run: |
        sudo mysql --host 127.0.0.1 --user=root --password=root testdb < database.sql

    # For server directory
    - name: Change into server directory
      run: cd server/
    - name: Install server dependencies
      run: npm install
      working-directory: ./server
    - name: Run server tests
      run: npm test
      working-directory: ./server
      env:
        MYSQL_HOST: localhost
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DB: testdb
